[package]
name = "drawio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

dfiles = { path = "../../" }
clap = "2.33"
anyhow = "1.0"
