[package]
name = "dfiles"
version = "0.1.0"
authors = ["Wayne Warren <wayne.warren.s@gmail.com>"]
edition = "2018"

[workspace]
members = [
  "app/chrome",
  "app/discord",
  "app/drawio",
  "app/firefox",
  "app/signal",
  "app/skype",
  "app/steam",
  "app/thinkorswim",
  "app/zoom",
]

[lib]
name = "dfiles"
path = "src/dfiles/mod.rs"

[dependencies]
shiplift = "0.5"
dockworker = { git = "https://github.com/waynr/dockworker", branch = "replace-fail-with-thiserror"}
tokio = "0.1"
serde = { version = "1.0", features = ["derive"] }
hyper = "0.12.35"
serde_json = "1.0"
serde_yaml = "0.8"
tempfile = "3.1.0"
tar = "0.4.26"
tzdata = "0.4.1"
thiserror = "1.0"
directories-next = "1.0"
dyn-clone = "1.0"

clap = "2.33"
users = "0.10.0"
