version: 2.1

workflows:
  my-workflow:
    jobs:
      - machine-job

jobs:
  machine-job:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker run -d --name db registry.digitalocean.com/meowmeow/node:latest
