version: 2

jobs:
  machine-job:
    docker:
      - image: 'registry.digitalocean.com/meowmeow/node:latest'
        aws_auth:
          aws_access_key_id: DOCKER_USERNAME
          aws_secret_access_key: DOCKER_PASSWORD
