[package]
name = "thinkorswim"
version = "0.1.0"
authors = ["Wayne Warren <wayne.warren.s@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

dfiles-core = { path = "../../dfiles-core" }
anyhow = "1.0"
